import { Product } from '../../domain/entities/Product';
import { Money } from '../../domain/value-objects/Money';

/**
 * High-fidelity initial seed catalog with realistic campus coffee & bakery products
 * utilizing verified CDN images and nutritional specs.
 */
export function createMockProducts(): Product[] {
  return [
    new Product({
      id: 'prod-combo-parciales',
      name: 'Combo Parciales: Latte Grande + Croissant Almendras',
      description: 'Café Latte Grande (16 oz) con leche a elección + Croissant recién salido del horno con finas láminas de almendras tostadas.',
      price: new Money(8800),
      category: 'COMBOS_ESTUDIANTILES',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRvRwwmYM8qzBnOAKJpW1t4QKp4CyPRlxb4d0Tqpb3d0Yo5oxS4HogPGoDE9m2xrdyN54cJqOpvGIs1y1D5Hvz5EuNJHHi3VWJhrpqo5d2WtrDJKELBTNk1q8u2vXSjgI6XdK_D3JMj9NKTBqMx8b7B8IYLvdFFxl2bLjNY5dv00UHmomy-0-c3CMfyuwN_FkfuHvW6VFAGDxmHWHABbP_B_7u6Oue8egufysBhY-5DjXM65Zmw0AN',
      preparationTimeMinutes: 3,
      calories: 450,
      dietaryBadge: 'Especial Parciales',
      isAvailable: true,
      isPopular: true,
      stockQuantity: 40,
      tags: ['Populares', 'Express', 'Combo Ahorro', 'Parciales'],
    }),
    new Product({
      id: 'prod-latte-caramelo',
      name: 'Latte Caramelo Artesanal',
      description: 'Doble shot de espresso premium origen Huila, leche vaporizada y salsa de caramelo casera elaborada a fuego lento.',
      price: new Money(6200),
      category: 'CAFE_ESPECIALIDAD',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClGSzbNDGQ4hr_Nm2jjZ-GllGs8qS-_OZRHFVUfQoGyIGQPuYo7pIAtjG_3bHhk5vvolznRJcQirGlIVOKzMvgVNrBrEEj0IZr5Ay5F3O716eh-1iJQBoCfMyNb_cqBHSAyMxEXy24mYFN11s-mnkQ_sgbouVMEA_Az7oprqcq5uVRlNWqZRoaUHLGnBgJRg-iLaVZZgc22WC5EVWmiZKL9I0vtOE2sd7uoNVLndHsilz-DbEb6f8L',
      preparationTimeMinutes: 4,
      calories: 190,
      dietaryBadge: 'Grano Huila',
      isAvailable: true,
      isPopular: true,
      stockQuantity: 65,
      tags: ['Populares', 'Express', 'Caliente'],
    }),
    new Product({
      id: 'prod-cold-brew',
      name: 'Cold Brew Vainilla Espresso',
      description: 'Extracción en frío durante 18 horas de granos selectos de altura, toque de sirope de vainilla bourbon y hielo cristalino.',
      price: new Money(7500),
      category: 'BEBIDAS_FRIAS',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAwv62IDP-2Tcb43JITxu5KIMyc9kTKEH8wGT8Pe2rgZSnQjzm9EbRsu-wsSSDUg8XBgT8-dtOHBR9AAA81SC344t1MgsaUGNpXZTpMKH4l5DOsW0hmvg9_FVMx-sZJsJaL_GvAzNfczbX33b8BXLW3yun4tVxYaatYrWCU1km-gL98Tu5wMJ63S-D38SVoEcJtsryJTerKdCuOkFVpT9Nbl6rBCM3C_EtVwwZe5ze4YXDajmBoG3NI',
      preparationTimeMinutes: 3,
      calories: 120,
      dietaryBadge: 'Macerado 18h',
      isAvailable: true,
      isPopular: true,
      stockQuantity: 30,
      tags: ['Express', 'Frío', 'Alta Cafeína'],
    }),
    new Product({
      id: 'prod-croissant',
      name: 'Croissant de Mantequilla Horneado',
      description: 'Hojaldrado tradicional francés elaborado artesanalmente cada dos horas en el obrador de la facultad.',
      price: new Money(4800),
      category: 'REPOSTERIA',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD9LGNGbnEVSFiwfQkLXtrrvf48I1OkmHoSqAd6msiG6g2xuWYwd_vyQAkzYCuTO6aLJEampGwUA6nBit2IsVB9X9l87Hdcm43nasAvlC3ufPse2QY9SfzG_JGO9gK3A7OEuhMFUNbgrq7NId4F3MNMF0QRfIXOBLpIhr97Bb1c8PuxW3Q-9OkAWh1XiJ0-DF1KVSy_Lm6r_DaVJdMUWZ-dXNNa5bQTRvzx7fOPxujH-yZJvLLcUkHC',
      preparationTimeMinutes: 2,
      calories: 290,
      dietaryBadge: '100% Mantequilla',
      isAvailable: true,
      isPopular: true,
      stockQuantity: 25,
      tags: ['Express', 'Vegetariano', 'Horneado'],
    }),
    new Product({
      id: 'prod-muffin-arandanos',
      name: 'Muffin de Arándanos & Avena Integral',
      description: 'Masa suave horneada con arándanos silvestres frescos, canela de Ceilán y copos enteros de avena.',
      price: new Money(5000),
      category: 'REPOSTERIA',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCNBlR8nieXQFSDJD_lCrBu_b2EDgJWJDZXUaEZSz7_xg5V53E37Q-mqR_MbcolRV4-61fVb4a4TzWRUBjEReLWV5NaSA2-7bqDo7Yj_cNa3yF0qU5mBUt3eaGT43tEcufkN9us9d1fh_7OMqMeJGU5JsGQTjBqGV_WQKRwowTIdK-OH7dLNcu8l5xItUdGwwsBexts1N8FXIArYLDSeiXT0qw_jM2xv0LIxk91jQHVkGh7rRWJ_Fcr',
      preparationTimeMinutes: 1,
      calories: 260,
      dietaryBadge: 'Bajo en azúcar',
      isAvailable: true,
      isPopular: false,
      stockQuantity: 18,
      tags: ['Express', 'Vegetariano'],
    }),
    new Product({
      id: 'prod-sandwich-pavo',
      name: 'Sándwich Pavo & Queso Gouda en Brioche',
      description: 'Pechuga de pavo ahumada artesanal, queso gouda fundido, hojas verdes tiernas y mayonesa dijon en pan brioche.',
      price: new Money(9800),
      category: 'SANDWICHES_SALADOS',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAwGxVto9aEcwVIb5qxncQW42XRDXkzthyUjwU-B92MYX7pwXRRl0lY4LjN3VBaFUU34I5KDG0BP-mpDsl79wEB1juPrPXMIZzR8aCmYMRUdnaFiB82F3Wh3f033TDb-p6JdJiefHsRp7mW2cUj4A60PCZ9XmjT2xeIjEE5tjUcqJPZKnZF2DQRheTqrxve4Hbogpz1XYaYDC2goQAxdLofkVE6Duhw7Is61BZ-Olmo5uHEihbg-9FA',
      preparationTimeMinutes: 7,
      calories: 480,
      dietaryBadge: '24g Proteína',
      isAvailable: true,
      isPopular: true,
      stockQuantity: 20,
      tags: ['Almuerzo', 'Proteína'],
    }),
    new Product({
      id: 'prod-bowl-yogur',
      name: 'Bowl Yogur Griego, Fresas & Granola',
      description: 'Yogur artesanal colado sin azúcar, fresas del día, arándanos, semillas de chía y miel pura de abejas campus.',
      price: new Money(7200),
      category: 'REPOSTERIA',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDSN2raPu8QFcarPRipdlQPh7S4QezF0VV6_aPEjofIplKSpzSWEMTYap8GDFJW4gTSW50ozbpgI6CE9jRRjZBSomi_kJ-QHqbMhkk7SwFY8aywZZsEIkhc3ASpZnYSI3lI7q1MCWsS2GsH5cc_a6a8amf7h6_LAnXhsmfiRiA4bmB8IBItjkbY9oxcLdL7q-nPWB6RPQAO_JbzSUOvHc-4dWAKm_hUUPm_4sej_OeWZoG0Hbs_ZRMc',
      preparationTimeMinutes: 5,
      calories: 310,
      dietaryBadge: 'Fit & Probiótico',
      isAvailable: true,
      isPopular: false,
      stockQuantity: 15,
      tags: ['Vegetariano', 'Fit'],
    }),
    new Product({
      id: 'prod-combo-desayuno',
      name: 'Combo Desayuno: Americano Doble + Empanada Horneada',
      description: 'Americano Doble recién filtrado acompañado de empanada campesina horneada crujiente con ají casero suave.',
      price: new Money(8000),
      category: 'COMBOS_ESTUDIANTILES',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJwEFJ3j5UtsmQ2WDHGv56sdjk1x2pNCDhEEh923QJffb3ag8ajav3opcZrMPYGG6CJ09hvL-nGOeMocx7LU254AM0t3Q67pQaiEi77WM03H9nf56t8ptNq7otA3Du37nk7t3RtoaHfcqc0_TPfcFuH-OhD3wBKbeHMeNLpAXty3MCLEziZ1B6sEP38UE4Eoyg-8nFwS0wLCXBKSPW4mkzm48-y0HAibPP6eSanLrDHDhCAbnVLNqq',
      preparationTimeMinutes: 3,
      calories: 340,
      dietaryBadge: 'Combo Ahorro',
      isAvailable: true,
      isPopular: true,
      stockQuantity: 35,
      tags: ['Populares', 'Express', 'Combo Ahorro'],
    }),
    new Product({
      id: 'prod-matcha-latte',
      name: 'Matcha Latte Ceremonial Uji',
      description: 'Té verde matcha de ceremonia batido en agua tibia con leche de avena vaporizada y toque sutil de sirope de agave.',
      price: new Money(7800),
      category: 'BEBIDAS_FRIAS',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-Ya4cR8N7DCInlKtiM9evHSxaEtqwAVGw8Js5bkHemEX3ISI3IncAfuOcZTu-qIw4YvhJ6yV_MGSyDD-MYMELxbHAMV7QxTrzS3nvtfp9jEtZRy5iX0tBM4FpIlClETFMfXxFALOZedwGwjrFrt4N0YXUBl2rMYwxVMkNZGiXlnoRv6Li6cELmX1lPAaNzTF2IPDz3BHakdsXPZvcmzTKsIQ-R3It93d1ln9bdNSi4QVUo5Ybr9c3',
      preparationTimeMinutes: 4,
      calories: 160,
      dietaryBadge: 'Matcha Uji',
      isAvailable: true,
      isPopular: false,
      stockQuantity: 22,
      tags: ['Vegetariano', 'Antioxidante'],
    }),
  ];
}
